OS-8499: non-flexible_disk bhyve can't set indestructible_zoneroot
TritonDataCenter/smartos-live pull request #1082
Opened 2023-11-13 20:16 UTC by marsell

With this change the refreservation on the zoneroot is now 1MiB smaller than before.

Before this patch:

```
[root@e4-43-4b-86-72-ec (ro-1) ~]# zfs get -r refreservation zones/781a2156-b2db-4b88-9bda-01626c900f30
NAME                                              PROPERTY        VALUE      SOURCE
zones/781a2156-b2db-4b88-9bda-01626c900f30        refreservation  1G         local
zones/781a2156-b2db-4b88-9bda-01626c900f30/disk0  refreservation  11.3G      local
zones/781a2156-b2db-4b88-9bda-01626c900f30/disk1  refreservation  54.9G      local
````

After (new VM with same image and package):

```
[root@e4-43-4b-86-72-ec (ro-1) ~]# zfs get -r refreservation zones/654393de-51ad-4bfd-b718-a58ab67aa383
NAME                                              PROPERTY        VALUE      SOURCE
zones/654393de-51ad-4bfd-b718-a58ab67aa383        refreservation  1023M      local
zones/654393de-51ad-4bfd-b718-a58ab67aa383/disk0  refreservation  11.3G      local
zones/654393de-51ad-4bfd-b718-a58ab67aa383/disk1  refreservation  54.9G      local
```

This allows vmadm to set indestructible_zoneroot:

```
[root@e4-43-4b-86-72-ec (ro-1) ~]# zfs list zones/654393de-51ad-4bfd-b718-a58ab67aa383@indestructible
cannot open 'zones/654393de-51ad-4bfd-b718-a58ab67aa383@indestructible': dataset does not exist
[root@e4-43-4b-86-72-ec (ro-1) ~]# vmadm update 654393de-51ad-4bfd-b718-a58ab67aa383 indestructible_zoneroot=true
Successfully updated VM 654393de-51ad-4bfd-b718-a58ab67aa383
[root@e4-43-4b-86-72-ec (ro-1) ~]# zfs list zones/654393de-51ad-4bfd-b718-a58ab67aa383@indestructible
NAME                                                        USED  AVAIL     REFER  MOUNTPOINT
zones/654393de-51ad-4bfd-b718-a58ab67aa383@indestructible      0      -      128K  -
[root@e4-43-4b-86-72-ec (ro-1) ~]# vmadm update 654393de-51ad-4bfd-b718-a58ab67aa383 indestructible_zoneroot=false
Successfully updated VM 654393de-51ad-4bfd-b718-a58ab67aa383
[root@e4-43-4b-86-72-ec (ro-1) ~]# zfs list zones/654393de-51ad-4bfd-b718-a58ab67aa383@indestructible
cannot open 'zones/654393de-51ad-4bfd-b718-a58ab67aa383@indestructible': dataset does not exist
```

2023-11-13 20:25 UTC, marsell commented
Probably too defensively programmed -- I don't see how we could have a maxQuota so small that Math.max() is needed -- but I've left that in there.

2023-11-13 20:51 UTC, bahamat commented
> Probably too defensively programmed -- I don't see how we could have a maxQuota so small that Math.max() is needed -- but I've left that in there.

For standalone SmartOS, it's common for VMs to be created without an explicit quota. So we need it in there in case it hasn't already been specified.

2023-11-13 21:11 UTC, bahamat requested changes

2023-11-13 21:38 UTC, marsell commented on src/vm/node_modules/VM.js
> + * Copyright Spearhead Systems SRL.
Well, that's a bit embarrassing. Fixed.

2023-11-15 17:37 UTC, bahamat approved these changes

2023-11-15 17:38 UTC, merged

2023-11-15 18:16 UTC, marsell commented
Confirming this works with platform in experimental platform:

```
[root@24-6e-96-5e-b3-9c (ro-1) ~]# zfs get -r refreservation zones/723174b6-2abf-4183-9289-44a68aff9404
NAME                                              PROPERTY        VALUE      SOURCE
zones/723174b6-2abf-4183-9289-44a68aff9404        refreservation  1023M      local
zones/723174b6-2abf-4183-9289-44a68aff9404/disk0  refreservation  10.6G      local
zones/723174b6-2abf-4183-9289-44a68aff9404/disk1  refreservation  51.6G      local
[root@24-6e-96-5e-b3-9c (ro-1) ~]# zfs list zones/723174b6-2abf-4183-9289-44a68aff9404@indestructible
cannot open 'zones/723174b6-2abf-4183-9289-44a68aff9404@indestructible': dataset does not exist
[root@24-6e-96-5e-b3-9c (ro-1) ~]# vmadm update 723174b6-2abf-4183-9289-44a68aff9404 indestructible_zoneroot=true
Successfully updated VM 723174b6-2abf-4183-9289-44a68aff9404
[root@24-6e-96-5e-b3-9c (ro-1) ~]# zfs list zones/723174b6-2abf-4183-9289-44a68aff9404@indestructible
NAME                                                        USED  AVAIL     REFER  MOUNTPOINT
zones/723174b6-2abf-4183-9289-44a68aff9404@indestructible      0      -      200K  -
[root@24-6e-96-5e-b3-9c (ro-1) ~]# vmadm update 723174b6-2abf-4183-9289-44a68aff9404 indestructible_zoneroot=false
Successfully updated VM 723174b6-2abf-4183-9289-44a68aff9404
[root@24-6e-96-5e-b3-9c (ro-1) ~]# zfs list zones/723174b6-2abf-4183-9289-44a68aff9404@indestructible
cannot open 'zones/723174b6-2abf-4183-9289-44a68aff9404@indestructible': dataset does not exist
```